# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: karie moorman
#description: Linguistics | Cognitive Science | Data Science & Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kariemoorman.com" # the base hostname & protocol for your site
github_username: kariemoorman
linkedin_username: karie-moorman-82002447
email:  kariemoorman@proton.me
permalink: /:year/:month/:day/:title

theme-dark: false #Set to true to change to dark website theme
#paginate: 5
#plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
